# This workflow will check environment before continue

name: Check environment

on:
  push:
    branches: [ main ]

jobs:
  check_environment:

    runs-on: bd-self-hosted-stage

    steps:
    - uses: actions/checkout@v2

    - name: Test Env
      run: |
        python3 -V
        pytest -V

    - name: Get PR Author Email Address
      run: |
        echo "The name of the pusher: ${{ github.event.pusher.name }}"
        echo "The email of the pusher: ${{ github.event.pusher.email }}"

    - name: Test with pytest
      run: |
        export DATABRICKS_HOST="$(aws secretsmanager get-secret-value  --secret-id /bigdata/secret_keys  --query SecretString --output text | jq -r .databricks_workspace_host)"
        export DATABRICKS_TOKEN="$(aws secretsmanager get-secret-value  --secret-id /bigdata/secret_keys  --query SecretString --output text | jq -r .databricks_token)"
        export ENVIRONMENT="production"
        echo $DATABRICKS_HOST
        echo $DATABRICKS_TOKEN
        pytest ./tests/environment/test_environment.py -v --basetemp=/tmp --tb=short
