name: tfrs-two-tower-gift
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - matplotlib==3.5.2
      - mlflow==1.26.1
      - pandas==1.3.4
      - numpy==1.22
      - tensorflow==2.8.0
      - tensorflow-recommenders==0.6.0
